### ISSUE TITLE
Erroring out when there's no CloudFront

### ISSUE THREAD

**Issue by zthomas** [opspresso/action-s3-sync#1]
I'm trying this action out right now and when I don't have CloudFront setup, it's throwing an error
```
An error occurred (NoSuchDistribution) when calling the CreateInvalidation operation: The specified distribution does not exist.
```
I looked at the shell script that you are using and when I ran the list cloudfront distribution command it returned null instead of empty string. 
```
aws cloudfront list-distributions --query "DistributionList.Items[].{Id:Id,Origin:Origins.Items[0].DomainName}[?contains(Origin,'${BUCKET}')] | [0]" --profile pushtable | awk '{print $1}'

$ null
```

on the next line, it's checking against empty string and continues to run the cloudfront command

**Comment by nalbam** [comment]
Sorry for the late reply.
I added one parameter to your request.

https://github.com/opspresso/action-s3-sync/commit/982c6711a526fafdee724969639ddb01e25617a9

Available since v0.2.3.

https://github.com/opspresso/action-s3-sync/releases/tag/v0.2.3
